/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Clases.Medida;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author PSN
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    private List<Medida> sistemaMonedas;
    
    public Inicio(List<Medida> sMonedas) {
        initComponents();
        this.sistemaMonedas = sMonedas;
    }

    public List<Medida> getSistemaMonedas() {
        return sistemaMonedas;
    }

    public void setSistemaMonedas(List<Medida> sistemaMonedas) {
        this.sistemaMonedas = sistemaMonedas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonMoneda = new javax.swing.JButton();
        ButtonMedida = new javax.swing.JButton();
        ButtonHorario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(400, 520));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 520));

        ButtonMoneda.setBackground(new java.awt.Color(51, 51, 51));
        ButtonMoneda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonMoneda.setForeground(new java.awt.Color(255, 255, 255));
        ButtonMoneda.setText("Monedas");
        ButtonMoneda.setFocusable(false);
        ButtonMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMonedaActionPerformed(evt);
            }
        });

        ButtonMedida.setBackground(new java.awt.Color(51, 51, 51));
        ButtonMedida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonMedida.setForeground(new java.awt.Color(255, 255, 255));
        ButtonMedida.setText("Medidas");
        ButtonMedida.setFocusable(false);
        ButtonMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMedidaActionPerformed(evt);
            }
        });

        ButtonHorario.setBackground(new java.awt.Color(51, 51, 51));
        ButtonHorario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonHorario.setForeground(new java.awt.Color(255, 255, 255));
        ButtonHorario.setText("Horario");
        ButtonHorario.setFocusable(false);
        ButtonHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHorarioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema de Conversión");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(130, 130, 130))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(ButtonMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(ButtonMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(ButtonHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMonedaActionPerformed
        Moneda interfazM = new Moneda(getSistemaMonedas());
        interfazM.setLocationRelativeTo(null);
        interfazM.setSize(520, 350);
        interfazM.setResizable(false);
        interfazM.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonMonedaActionPerformed

    private void ButtonMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMedidaActionPerformed
        // TODO add your handling code here:
        Distancia interfazD = new Distancia(getSistemaMonedas());
        interfazD.setLocationRelativeTo(null);
        interfazD.setSize(520, 350);
        interfazD.setResizable(false);
        interfazD.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonMedidaActionPerformed

    private void ButtonHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHorarioActionPerformed
        // TODO add your handling code here:
        Horario interfazH = new Horario(getSistemaMonedas());
        interfazH.setLocationRelativeTo(null);
        interfazH.setSize(532, 350);
        interfazH.setResizable(false);
        interfazH.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonHorarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonHorario;
    private javax.swing.JButton ButtonMedida;
    private javax.swing.JButton ButtonMoneda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
